package Contrat;


/**
* Contrat/_EtudiantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/


// Déclaration d'un type séquence
public class _EtudiantStub extends org.omg.CORBA.portable.ObjectImpl implements Contrat.Etudiant
{

  public void Ajouter_une_epreuve (String nom, double note, double coefficient)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Ajouter_une_epreuve", true);
                $out.write_string (nom);
                $out.write_double (note);
                $out.write_double (coefficient);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                Ajouter_une_epreuve (nom, note, coefficient        );
            } finally {
                _releaseReply ($in);
            }
  } // Ajouter_une_epreuve

  public String[] Liste_des_epreuves ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Liste_des_epreuves", true);
                $in = _invoke ($out);
                String $result[] = Contrat.StringSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Liste_des_epreuves (        );
            } finally {
                _releaseReply ($in);
            }
  } // Liste_des_epreuves


  // Utilisation du type défini
  public double Calculer_la_moyenne ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Calculer_la_moyenne", true);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Calculer_la_moyenne (        );
            } finally {
                _releaseReply ($in);
            }
  } // Calculer_la_moyenne

  public void Emprunter_un_livre (String nom, String auteur, String collection, String datePublication)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Emprunter_un_livre", true);
                $out.write_string (nom);
                $out.write_string (auteur);
                $out.write_string (collection);
                $out.write_string (datePublication);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                Emprunter_un_livre (nom, auteur, collection, datePublication        );
            } finally {
                _releaseReply ($in);
            }
  } // Emprunter_un_livre

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Contrat/Etudiant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EtudiantStub
