package Contrat;


/**
* Contrat/EtudiantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/


// Déclaration d'un type séquence
abstract public class EtudiantHelper
{
  private static String  _id = "IDL:Contrat/Etudiant:1.0";

  public static void insert (org.omg.CORBA.Any a, Contrat.Etudiant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Contrat.Etudiant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Contrat.EtudiantHelper.id (), "Etudiant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Contrat.Etudiant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EtudiantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Contrat.Etudiant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Contrat.Etudiant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Contrat.Etudiant)
      return (Contrat.Etudiant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Contrat._EtudiantStub stub = new Contrat._EtudiantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Contrat.Etudiant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Contrat.Etudiant)
      return (Contrat.Etudiant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Contrat._EtudiantStub stub = new Contrat._EtudiantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
