package Contrat;


/**
* Contrat/EtudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/


// Déclaration d'un type séquence
public interface EtudiantOperations 
{
  void Ajouter_une_epreuve (String nom, double note, double coefficient);
  String[] Liste_des_epreuves ();

  // Utilisation du type défini
  double Calculer_la_moyenne ();
  void Emprunter_un_livre (String nom, String auteur, String collection, String datePublication);
} // interface EtudiantOperations
