package Contrat;

/**
* Contrat/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/


// Déclaration d'un type séquence
public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Contrat.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (Contrat.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Contrat.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Contrat.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Contrat.EtudiantHelper.type ();
  }

}
