package Contrat;


/**
* Contrat/Promotion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/

public interface Promotion extends PromotionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Promotion
