package Contrat;

/**
* Contrat/PromotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/

public final class PromotionHolder implements org.omg.CORBA.portable.Streamable
{
  public Contrat.Promotion value = null;

  public PromotionHolder ()
  {
  }

  public PromotionHolder (Contrat.Promotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Contrat.PromotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Contrat.PromotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Contrat.PromotionHelper.type ();
  }

}
