package Contrat;


/**
* Contrat/StringSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 3:36:24 PM WAT
*/

public final class StringSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringSequenceHolder ()
  {
  }

  public StringSequenceHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Contrat.StringSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Contrat.StringSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Contrat.StringSequenceHelper.type ();
  }

}
